### ISSUE TITLE
Terraform 0.12 compatibility

### ISSUE THREAD

**Issue by calmyournerves** [cloudscale-ch/terraform-provider-cloudscale#18]
Hey there 👋

This provider does not seem to be compatible with Terraform 0.12.x yet. Are there any plans for it?

Thanks!

**Comment by davidhalter** [comment]
Hey @calmyournerves 

I have to make a new release, but basically it should be ready for Terraform 0.12.x. There shouldn't be any major changes needed (anymore).

I will let you know here. Expect this to be done in the week of 4.-10. November. Is this early enough for you?

**Comment by calmyournerves** [comment]
Thanks @davidhalter, that sounds good!

**Comment by davidhalter** [comment]
@calmyournerves I just implemented multiple zones in terraform. Once we merged this, I will ask HashiCorp for a release, which includes Terraform 0.12.x support.

I expect this to take yet another week. https://github.com/terraform-providers/terraform-provider-cloudscale/pull/19

**Comment by calmyournerves** [comment]
👌 Thanks for the update @davidhalter!

**Comment by davidhalter** [comment]
@calmyournerves We finally managed to get it publish with HashiCorp.

Use `terraform0.12.16 init -upgrade` to upgrade. Zones are now part of terraform and we're working on network management with terraform (currently).

Let me know if you encounter any problems.

PS: Sorry for the delay, I was sick two weeks ago and then there were some issues with the builds.

**Comment by calmyournerves** [comment]
Thanks! Works like a charm so far :)
