### ISSUE TITLE
[Feature Request] Data Source

### ISSUE THREAD

**Issue by splattner** [cloudscale-ch/terraform-provider-cloudscale#40]
It would be nice to also have Data Sources and not only Resources.

Why?
I create a k8s cluster using the Rancher cloudscale.ch integration with terraform and I need to access the UUID of the created vm's. The UUID then is used to deploy our failover IP setup with notify script to your API
Unfortunatly the rancher2_* module do not return the UUID for the nodes in a node_pool. Therefore I'd like to define the vm as a data source "cloudscale_server" with the vm name as identifier.

**Comment by alakae** [comment]
Hey @splattner

I have created an internal ticket for this. We will evaluate when and if we do it.

**Comment by simu** [comment]
Hey @alakae, any updates on this one? We've come across a situation where it would be very helpful if we had data sources to extract the CIDR of a private subnet which is supplied externally, and used in Terraform via its UUID.

**Comment by davidhalter** [comment]
Hi @simu 

I have just started looking into this. However don't expect it in the next few days.

**Comment by davidhalter** [comment]
@simu @splattner Do you guys work with with datasource lists as well or are single objects good enough?

Most data source providers just provide access to single objects. However some provide access to a filtered list.

The difference is basically this:

Single:

resource "aws_instance" "web" {
  ami           = data.aws_ami.web.id
  instance_type = "t1.micro"
}

List:

```
data "aws_ami" "web" {
  filter {
    name   = "state"
    values = ["available"]
  }

  filter {
    name   = "tag:Component"
    values = ["web"]
  }

  most_recent = true
}
```

I'm currently only working on the "single" version.

**Comment by simu** [comment]
In my experience, single objects are good enough for most use-cases.

Certainly for the specific use-case of importing an existing private network, single objects is sufficient.

**Comment by splattner** [comment]
I agree, I think single object is sufficient.

**Comment by davidhalter** [comment]
Data sources have been implemented for all resources:

https://registry.terraform.io/providers/cloudscale-ch/cloudscale/latest/docs

Have fun using it :).
