### ISSUE TITLE
[Feature Request] Support import

### ISSUE THREAD

**Issue by DebakelOrakel** [cloudscale-ch/terraform-provider-cloudscale#42]
If possible, it would be nice to be able to import "legacy" resources into terraform.

```
Error: resource cloudscale_network doesn't support import
```

**Comment by alakae** [comment]
Hi @DebakelOrakel 

Thanks for your comment!

I think this is a duplicate of #40. This feature is still in out backlog.
I hope we'll have time to implement it soon.

**Comment by alakae** [comment]
I realised that import and data sources are similar, but different features. Therefore, reopening this issue.
Sorry for the inconvenience.

**Comment by davidhalter** [comment]
Imports have been implemented for all resources except custom images:

https://registry.terraform.io/providers/cloudscale-ch/cloudscale/latest/docs

Have fun using it :).
