### ISSUE TITLE
License of the project?

### ISSUE THREAD

**Issue by Mic92** [cloudscale-ch/terraform-provider-cloudscale#66]
We currently exclude this package from nixpkgs because the project comes without a license (https://github.com/NixOS/nixpkgs/pull/203000).
Could you add a license for the project?

**Comment by davidhalter** [comment]
We will add a license. In the meantime, know that it will probably be MIT licensed.

**Comment by davidhalter** [comment]
Added an [MIT License](https://github.com/cloudscale-ch/terraform-provider-cloudscale/blob/master/LICENSE).

Thanks for letting us know.
