### ISSUE TITLE
Accessing a server's public IPv4/IPv6

### ISSUE THREAD

**Issue by ferdinandhuebner** [cloudscale-ch/terraform-provider-cloudscale#7]
I want to access the public IPv4 and IPv6 addresses of a server to deploy DNS records after the server was created.

However, I am having trouble accessing the IP addresses because they are returned in a list of maps. As far as I understand, I can't filter a list of maps with current stable versions of terraform. 
This would only be possible with the new HCL engine that is going to be introduced with terraform 0.12. Even with the new HCL engine, accessing the public IP addresses would be unnecessary complex.

Other providers, for example the openstack provider, [expose the first detected IPv4 and IPv6 in a plain string field](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#access_ip_v4). 
Adding those fields to the cloudscale.ch provider would be trivial. There is already existing code (`findIPv4AddrByType` and `findIPv6AddrByType`) that is adding the first public IPv4 or IPv6 address to the connection info for the server resource.

Would the maintainers of this provider accept a pull request that exposes the first public IPv4 and IPv6 as a string field?

**Comment by davidhalter** [comment]
I personally don't mind and understand your concern.
