### ISSUE TITLE
Provider does not re-create deleted resources

### ISSUE THREAD

**Issue by ferdinandhuebner** [cloudscale-ch/terraform-provider-cloudscale#9]
### Steps to reproduce:

- Create a new server with terraform
- Delete the server through the cloudscale.ch web UI
- Run `terraform plan`

### Expected results: 

Terraform detects that the resource no longer exists and the plan would recreate the server

### Actual results:

`terraform plan` returns with exit code `1` and the following error message:

```
cloudscale_server.web-worker01: Refreshing state... (ID: 8befb05e-025c-431d-bcbb-abd8f4fb2593)

Error: Error refreshing state: 1 error(s) occurred:

* cloudscale_server.web-worker01: 1 error(s) occurred:

* cloudscale_server.web-worker01: cloudscale_server.web-worker01: Error retrieving server: detail: Not found
```
### Cause:

Not found detection in `resource_cloudscale_server.go` checks for the string `detail: Not Found.` but the API seems to return `detail: Not found`:

https://github.com/terraform-providers/terraform-provider-cloudscale/blob/33b91a5dcd600d0299c7a7c0ab7c684fa69e8e0d/cloudscale/resource_cloudscale_server.go#L271 

Newer versions of the cloudscale-go-sdk expose the HTTP status code. This could be used as an alternative to string matching.

**Comment by davidhalter** [comment]
I agree that we should check for the HTTP status code.
